apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-postgres
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rhn-consulting-kemori/demo-argocd
    path: demo-itst/apps/database/base
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-itst-2
