apiVersion: batch/v1
kind: Job
metadata:
  name: insert-table-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app: insert-table-job
    app.openshift.io/runtime: other-linux
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: insert-table-job
          image: quay.io/rhn_consulting_kemori/insert_table_demoapl:latest
          imagePullPolicy: Always
          env:
            - name: DB_USER
              value: "test"
            - name: DB_PASSWORD
              value: "test"
            - name: DB_SERVERNAME
              value: "postgresql.demo-itst-2.svc.cluster.local"
            - name: DB_PORTNUMBER
              value: "5432"
