apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-create
spec:
  template:
    spec:
      containers:
        - name: pay-create
          env:
            # 想定日を変更する
            - name: SIMURATION_DATE
              value: "20250512"
