apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-apl-viewer
  labels:
    app: demo-apl-viewer
    app.openshift.io/runtime: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-apl-viewer
  template:
    metadata:
      labels:
        app: demo-apl-viewer
    spec:
      containers:
        - name: demo-apl-viewer
          image: quay.io/rhn_consulting_kemori/demo-apl-viewer:1.1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8288
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-params
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-params
                  key: DB_NAME
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: database-params
                  key: DB_PASS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-params
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: database-params
                  key: DB_USER
