apiVersion: v1
kind: Service
metadata:
  name: data-setup
  labels:
    app: data-setup
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  ports:
    - name: 8090-tcp
      protocol: TCP
      port: 8090
      targetPort: 8090
      sessionAffinity: None
      selector:
        app: data-setup
