project: default
source:
  repoURL: https://github.com/rhn-consulting-kemori/demo-argocd
  path: demo-itst/apps/database/base
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: demo-itst-2