project: default
source:
  repoURL: https://github.com/rhn-consulting-kemori/demo-argocd
  path: demo-itst/apps/online-apps/overlays/itst/itst-2
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: demo-itst-2
